Repository Groupease/groupease, pull requests merged in 2018-04, with the labels that each got.

#34 Issue #33: Client Save User
  groupease-client/src/app/app.module.ts
  groupease-client/src/app/auth/auth.service.spec.ts
  groupease-client/src/app/auth/auth.service.ts
  groupease-client/src/app/user.service.spec.ts
  groupease-client/src/app/user.service.ts
  groupease-client/src/app/user.ts
  groupease-server/src/main/java/io/github/groupease/channel/JpaChannelDao.java
  groupease-server/src/main/java/io/github/groupease/user/JpaUserDao.java
Labels: review

#37 Issue #16: List all channels for a channel member
  groupease-server/src/main/java/io/github/groupease/channel/ChannelDao.java
  groupease-server/src/main/java/io/github/groupease/channel/ChannelService.java
  groupease-server/src/main/java/io/github/groupease/channel/ChannelWebService.java
  groupease-server/src/main/java/io/github/groupease/channel/DefaultChannelService.java
  groupease-server/src/main/java/io/github/groupease/channel/JpaChannelDao.java
  groupease-server/src/main/java/io/github/groupease/channel/MockChannelDao.java
  groupease-server/src/test/java/io/github/groupease/channel/ChannelWebServiceTest.java
Labels: review

#36 Issues 22-24,26 - Channel Invitation, Join Request, Groups REST services and related
  db/migration/V1__Initial_Schema.sql
  groupease-server/src/main/java/io/github/groupease/db/ChannelInvitationDao.java
  groupease-server/src/main/java/io/github/groupease/db/ChannelJoinRequestDao.java
  groupease-server/src/main/java/io/github/groupease/db/GroupDao.java
  groupease-server/src/main/java/io/github/groupease/db/GroupInvitationDao.java
  groupease-server/src/main/java/io/github/groupease/db/GroupJoinRequestDao.java
  groupease-server/src/main/java/io/github/groupease/db/GroupeaseUserDao.java
  groupease-server/src/main/java/io/github/groupease/db/MemberDao.java
  groupease-server/src/main/java/io/github/groupease/exception/AlreadyMemberException.java
  groupease-server/src/main/java/io/github/groupease/exception/ChannelIdMismatchException.java
  groupease-server/src/main/java/io/github/groupease/exception/ChannelInvitationNotFoundException.java
  groupease-server/src/main/java/io/github/groupease/exception/ChannelJoinRequestNotFoundException.java
  groupease-server/src/main/java/io/github/groupease/exception/GroupIdMismatchException.java
  groupease-server/src/main/java/io/github/groupease/exception/GroupNameConflictException.java
  groupease-server/src/main/java/io/github/groupease/exception/GroupNameMissingException.java
  groupease-server/src/main/java/io/github/groupease/exception/GroupNotFoundException.java
  groupease-server/src/main/java/io/github/groupease/exception/NotChannelMemberException.java
  groupease-server/src/main/java/io/github/groupease/exception/NotChannelOwnerException.java
  groupease-server/src/main/java/io/github/groupease/exception/NotGroupMemberException.java
  groupease-server/src/main/java/io/github/groupease/exception/NotSenderException.java
  groupease-server/src/main/java/io/github/groupease/exception/UserMismatchException.java
  groupease-server/src/main/java/io/github/groupease/group/GroupDao.java
  groupease-server/src/main/java/io/github/groupease/group/GroupWebService.java
  groupease-server/src/main/java/io/github/groupease/model/Channel.java
  groupease-server/src/main/java/io/github/groupease/model/ChannelInvitation.java
  groupease-server/src/main/java/io/github/groupease/model/ChannelJoinRequest.java
  groupease-server/src/main/java/io/github/groupease/model/Group.java
  groupease-server/src/main/java/io/github/groupease/model/GroupeaseUser.java
  groupease-server/src/main/java/io/github/groupease/model/LegacyUserProfileToDelete.java
  groupease-server/src/main/java/io/github/groupease/model/Member.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/ChannelInvitationService.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/ChannelJoinRequestService.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/GroupWebService.java
  groupease-server/src/main/java/io/github/groupease/util/ChannelInvitationCreateWrapper.java
  groupease-server/src/main/java/io/github/groupease/util/CommentWrapper.java
  groupease-server/src/main/java/io/github/groupease/util/GroupCreateWrapper.java
Labels: review

#42 Issue #40: Create Channel UI
  groupease-client/src/app/channel-directory/channel-creator/channel-creator.component.html
  groupease-client/src/app/channel-directory/channel-creator/channel-creator.component.scss
  groupease-client/src/app/channel-directory/channel-creator/channel-creator.component.spec.ts
  groupease-client/src/app/channel-directory/channel-creator/channel-creator.component.ts
  groupease-client/src/app/channel-directory/channel-directory-routing.module.ts
  groupease-client/src/app/channel-directory/channel-directory.module.ts
  groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.html
  groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.spec.ts
Labels: review

#45 Issue #43: Channel Join Request UI
  groupease-client/src/app/channel-admin/channel-admin.module.ts
  groupease-client/src/app/channel-admin/join-request-list/join-request-list.component.html
  groupease-client/src/app/channel-admin/join-request-list/join-request-list.component.scss
  groupease-client/src/app/channel-admin/join-request-list/join-request-list.component.spec.ts
  groupease-client/src/app/channel-admin/join-request-list/join-request-list.component.ts
  groupease-client/src/app/channel-directory/channel-directory.module.ts
  groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.html
  groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.scss
  groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.spec.ts
  groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.ts
  groupease-client/src/app/core/channel-join-request.service.spec.ts
  groupease-client/src/app/core/channel-join-request.service.ts
  groupease-client/src/app/core/channel-join-request.ts
  groupease-client/src/app/core/core.module.ts
  groupease-server/src/main/java/io/github/groupease/model/ChannelJoinRequest.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/ChannelJoinRequestService.java
  groupease-server/src/main/java/io/github/groupease/util/CommentWrapper.java
Labels: review

#44 Issue #27 - Group Invitation API
  db/migration/V1__Initial_Schema.sql
  groupease-server/src/main/java/io/github/groupease/db/GroupInvitationDao.java
  groupease-server/src/main/java/io/github/groupease/exception/GroupIdMissingException.java
  groupease-server/src/main/java/io/github/groupease/exception/GroupInvitationNotFoundException.java
  groupease-server/src/main/java/io/github/groupease/model/GroupInvitation.java
  groupease-server/src/main/java/io/github/groupease/model/GroupeaseUser.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/GroupInvitationService.java
Labels: review

#47 Additional "create" overload
  groupease-server/src/main/java/io/github/groupease/db/MemberDao.java
Labels: review

#48 Issue #46: Channel Invitation UI
  groupease-client/src/app/channel-admin/user-list/user-list.component.html
  groupease-client/src/app/channel-admin/user-list/user-list.component.scss
  groupease-client/src/app/channel-admin/user-list/user-list.component.spec.ts
  groupease-client/src/app/channel-admin/user-list/user-list.component.ts
  groupease-client/src/app/core/channel-invitation.service.spec.ts
  groupease-client/src/app/core/channel-invitation.service.ts
  groupease-client/src/app/core/channel-invitation.ts
  groupease-client/src/app/core/core.module.ts
  groupease-client/src/app/dashboard/dashboard.module.ts
  groupease-client/src/app/dashboard/invitation-list/invitation-list.component.html
  groupease-client/src/app/dashboard/invitation-list/invitation-list.component.scss
  groupease-client/src/app/dashboard/invitation-list/invitation-list.component.spec.ts
  groupease-client/src/app/dashboard/invitation-list/invitation-list.component.ts
  groupease-server/src/main/java/io/github/groupease/model/ChannelInvitation.java
  groupease-server/src/main/java/io/github/groupease/util/ChannelInvitationCreateWrapper.java
Labels: review

#49 Issue #41: New Channel Owner
  groupease-server/src/main/java/io/github/groupease/channel/ChannelEditByNonOwnerException.java
  groupease-server/src/main/java/io/github/groupease/channel/DefaultChannelService.java
  groupease-server/src/main/java/io/github/groupease/db/MemberDao.java
  groupease-server/src/main/java/io/github/groupease/model/Member.java
  groupease-server/src/test/java/io/github/groupease/GroupeaseTestGuiceModule.java
  groupease-server/src/test/java/io/github/groupease/channel/DefaultChannelServiceTest.java
Labels: review

#51 Issue #39: Dashboard Member Channels
  groupease-client/src/app/core/channel.service.spec.ts
  groupease-client/src/app/core/channel.service.ts
  groupease-client/src/app/dashboard/channel-list/channel-list.component.html
  groupease-client/src/app/dashboard/channel-list/channel-list.component.spec.ts
  groupease-client/src/app/dashboard/channel-list/channel-list.component.ts
  groupease-server/src/main/java/io/github/groupease/channel/ChannelDao.java
  groupease-server/src/main/java/io/github/groupease/channel/ChannelService.java
  groupease-server/src/main/java/io/github/groupease/channel/ChannelWebService.java
  groupease-server/src/main/java/io/github/groupease/channel/JpaChannelDao.java
Labels: review

#55 Issue #29 - Member leave group
  groupease-server/src/main/java/io/github/groupease/db/GroupDao.java
  groupease-server/src/main/java/io/github/groupease/exception/InvalidGroupModificationException.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/GroupWebService.java
  groupease-server/src/main/java/io/github/groupease/util/GroupCreateWrapper.java
Labels: review

#56 Issue #54: Group Details
  groupease-client/src/app/channel-group/channel-group-directory/channel-group-directory.component.html
  groupease-client/src/app/channel-group/channel-group-routing.module.ts
  groupease-client/src/app/channel-group/channel-group.module.ts
  groupease-client/src/app/channel-group/group-details-home/group-details-home.component.html
  groupease-client/src/app/channel-group/group-details-home/group-details-home.component.spec.ts
  groupease-client/src/app/channel-group/group-details-home/group-details-home.component.ts
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.html
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.scss
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.spec.ts
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.ts
  groupease-client/src/app/channel-group/group-details-requests/group-details-requests.component.html
  groupease-client/src/app/channel-group/group-details-requests/group-details-requests.component.scss
  groupease-client/src/app/channel-group/group-details-requests/group-details-requests.component.spec.ts
  groupease-client/src/app/channel-group/group-details-requests/group-details-requests.component.ts
  groupease-client/src/app/channel-group/group-details/group-details.component.html
  groupease-client/src/app/channel-group/group-details/group-details.component.ts
  groupease-client/src/app/channel-group/group-member-list/group-member-list.component.html
  groupease-client/src/app/channel-group/group-member-list/group-member-list.component.scss
  groupease-client/src/app/channel-group/group-member-list/group-member-list.component.spec.ts
  groupease-client/src/app/channel-group/group-member-list/group-member-list.component.ts
  groupease-client/src/app/channel-group/group-summary/group-summary.component.html
  groupease-client/src/app/channel-group/group-summary/group-summary.component.scss
  groupease-client/src/app/channel-group/group-summary/group-summary.component.spec.ts
  groupease-client/src/app/channel-group/group-summary/group-summary.component.ts
  groupease-server/src/main/java/io/github/groupease/model/GroupeaseUser.java
Labels: review

#65 Issue #61: Home Page
  groupease-client/src/app/app.component.html
  groupease-client/src/app/app.component.scss
  groupease-client/src/app/home/home.module.ts
  groupease-client/src/app/home/home/home.component.html
  groupease-client/src/app/home/home/home.component.scss
  groupease-client/src/app/home/home/home.component.spec.ts
  groupease-client/src/app/home/home/home.component.ts
  groupease-client/src/groupease-theme.scss
  groupease-client/src/material-theme-config.scss
  groupease-client/src/styles.scss
Labels: review

#67 Fix issue #50
  groupease-server/src/main/java/io/github/groupease/exception/DuplicateChannelInvitationException.java
  groupease-server/src/main/java/io/github/groupease/exception/DuplicateChannelJoinRequestException.java
  groupease-server/src/main/java/io/github/groupease/exception/DuplicateGroupInvitationException.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/ChannelInvitationService.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/ChannelJoinRequestService.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/GroupInvitationService.java
Labels: bug, review

#68 Issue #25: Channel Member API
  db/migration/V1__Initial_Schema.sql
  groupease-client/src/app/core/core.module.ts
  groupease-client/src/app/core/member.service.spec.ts
  groupease-client/src/app/core/member.service.ts
  groupease-client/src/app/core/member.ts
  groupease-server/src/main/java/io/github/groupease/channel/ChannelService.java
  groupease-server/src/main/java/io/github/groupease/channel/ChannelWebService.java
  groupease-server/src/main/java/io/github/groupease/channel/DefaultChannelService.java
  groupease-server/src/main/java/io/github/groupease/channel/JpaChannelDao.java
  groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberDeleteForbiddenException.java
  groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberGuiceModule.java
  groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberIdMismatchException.java
  groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberNotFoundException.java
  groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberService.java
  groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberWebService.java
  groupease-server/src/main/java/io/github/groupease/channelmember/DefaultChannelMemberService.java
  groupease-server/src/main/java/io/github/groupease/config/guice/GroupeaseGuiceModule.java
  groupease-server/src/main/java/io/github/groupease/db/ChannelJoinRequestDao.java
  groupease-server/src/main/java/io/github/groupease/db/GroupDao.java
  groupease-server/src/main/java/io/github/groupease/db/GroupeaseUserDao.java
  groupease-server/src/main/java/io/github/groupease/db/MemberDao.java
  groupease-server/src/main/java/io/github/groupease/model/Channel.java
  groupease-server/src/main/java/io/github/groupease/model/Member.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/GroupInvitationService.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/GroupWebService.java
  groupease-server/src/main/java/io/github/groupease/user/DefaultUserService.java
  groupease-server/src/main/java/io/github/groupease/user/JpaUserDao.java
  groupease-server/src/main/java/io/github/groupease/user/UserWebService.java
  groupease-server/src/test/java/io/github/groupease/channel/DefaultChannelServiceTest.java
Labels: review

#72 Issue #57: Edit Member Profile
  groupease-client/src/app/channel-group/group-member-list/group-member-list.component.html
  groupease-client/src/app/channel-profile/channel-profile-routing.module.ts
  groupease-client/src/app/channel-profile/channel-profile.module.ts
  groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.html
  groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.scss
  groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.spec.ts
  groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.ts
  groupease-client/src/app/channel-profile/profile-form/profile-form.component.html
  groupease-client/src/app/channel-profile/profile-form/profile-form.component.scss
  groupease-client/src/app/channel-profile/profile-form/profile-form.component.spec.ts
  groupease-client/src/app/channel-profile/profile-form/profile-form.component.ts
  groupease-client/src/app/channel-profile/profile-home/profile-home.component.html
  groupease-client/src/app/channel-profile/profile-home/profile-home.component.scss
  groupease-client/src/app/channel-profile/profile-home/profile-home.component.spec.ts
  groupease-client/src/app/channel-profile/profile-home/profile-home.component.ts
  groupease-client/src/app/channel/channel-navigation/channel-navigation.component.html
  groupease-client/src/app/channel/channel-routing.module.ts
Labels: review

#76 Issue #28 - Group Join Request API
  groupease-server/src/main/java/io/github/groupease/db/GroupJoinRequestDao.java
  groupease-server/src/main/java/io/github/groupease/exception/DuplicateGroupJoinRequestException.java
  groupease-server/src/main/java/io/github/groupease/exception/GroupJoinRequestNotFoundException.java
  groupease-server/src/main/java/io/github/groupease/model/GroupJoinRequest.java
  groupease-server/src/main/java/io/github/groupease/restendpoint/GroupJoinRequestService.java
Labels: blocking, review

#77 Issue #59: Group Invitation
  groupease-client/src/app/channel-group/group-details-home/group-details-home.component.ts
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.html
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.scss
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.spec.ts
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.ts
  groupease-client/src/app/core/core.module.ts
  groupease-client/src/app/core/group-invitation.service.spec.ts
  groupease-client/src/app/core/group-invitation.service.ts
  groupease-client/src/app/core/group-invitation.ts
Labels: review

#78 Issue #60: Group Invitation Response
  groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.ts
  groupease-client/src/app/channel-profile/channel-profile.module.ts
  groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.html
  groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.scss
  groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.spec.ts
  groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.ts
  groupease-client/src/app/core/group-invitation.service.ts
  groupease-client/src/app/core/group-invitation.ts
Labels: review

#80 Issue #69 & Issue #70
  groupease-server/src/main/java/io/github/groupease/channel/ChannelService.java
  groupease-server/src/main/java/io/github/groupease/channel/DefaultChannelService.java
  groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberNotOwnerException.java
  groupease-server/src/main/java/io/github/groupease/channelmember/DefaultChannelMemberService.java
Labels: review

#84 Issue #20: Adds Dropwizard Metrics
  groupease-server/build.gradle
  groupease-server/src/main/java/io/github/groupease/config/guice/GroupeaseContextListener.java
  groupease-server/src/main/java/io/github/groupease/config/guice/GroupeaseGuiceModule.java
  groupease-server/src/main/java/io/github/groupease/config/metrics/MetricsGuiceModule.java
  groupease-server/src/main/java/io/github/groupease/config/metrics/Slf4jReporterProvider.java
  groupease-server/src/main/resources/reference.conf
  groupease-server/src/main/webapp/WEB-INF/web.xml
Labels: review

#85 Issue #73: Admin Channel Members
  groupease-client/src/app/channel-admin/member-list/member-list.component.html
  groupease-client/src/app/channel-admin/member-list/member-list.component.scss
  groupease-client/src/app/channel-admin/member-list/member-list.component.spec.ts
  groupease-client/src/app/channel-admin/member-list/member-list.component.ts
Labels: review

#89 Issue #88: Stop Insterting Test Data into DB
  db/migration/V1__Initial_Schema.sql
Labels: review

#92 Issue #30: Stop Clearing DB
  build.gradle
Labels: review

#93 Issue-91: Loaderio Support
  groupease-server/src/main/webapp/loaderio-16e2f61c7a51dfebd94f965fd0e81f98.txt
Labels: review

#100 Issue #99: MIT License
  LICENSE
Labels: review
